using System;
using System.Buffers.Binary;
using System.Reflection;
using System.Security.Cryptography;

namespace SharpAstro.Color.Icc;

/// <summary>
/// Bundled ICC profiles. Callers that want their TIFF / PNG output to
/// round-trip through colour-managed viewers (PixInsight, Lightroom, browsers)
/// without supplying their own profile bytes can pass one of these directly
/// to <c>SharpAstro.Tiff.TiffPageOptions.IccProfile</c> or to the
/// <c>SharpAstro.Png.PngWriter.Encode(..., iccProfile)</c> overload.
///
/// The bundled sRGB profile is a 588-byte v4 profile generated by LittleCMS
/// (the same engine that ships in Pillow / GIMP / Krita). v4 is the modern
/// recommended encoding from the ICC and is round-tripped correctly by every
/// major image library; the binary blob lives at <c>sRGB-v4.icc</c> alongside
/// this source file and is loaded lazily on first access.
/// </summary>
public static class IccProfiles
{
    private static readonly Lazy<byte[]> _sRgbV4 = new(() => LoadEmbeddedResource("SharpAstro.Color.Icc.sRGB-v4.icc"));

    /// <summary>
    /// sRGB IEC61966-2.1 v4 ICC profile (588 bytes). Public domain — generated
    /// by LittleCMS. Use this when writing colour-managed output that should be
    /// interpreted as sRGB by downstream readers.
    /// </summary>
    public static ReadOnlyMemory<byte> SRgbV4 => _sRgbV4.Value;

    private static byte[] LoadEmbeddedResource(string logicalName)
    {
        var asm = typeof(IccProfiles).Assembly;
        using var stream = asm.GetManifestResourceStream(logicalName)
            ?? throw new InvalidOperationException($"Embedded resource '{logicalName}' not found in {asm.GetName().Name}.");
        using var ms = new MemoryStream(capacity: (int)stream.Length);
        stream.CopyTo(ms);
        return ms.ToArray();
    }

    /// <summary>
    /// Returns a copy of <paramref name="baseProfile"/> with an ICC v4.4
    /// <c>cicp</c> tag injected. Use this to layer H.273 colour-space
    /// signalling onto an existing ICC profile so HDR-aware readers
    /// (PixInsight, Affinity, recent Photoshop / ImageMagick) interpret
    /// the embedded file as wide-gamut / HDR, while readers that don't
    /// recognise the tag fall back to the profile body's curves + matrix.
    /// </summary>
    /// <param name="baseProfile">A complete ICC profile (header + tag
    /// table + tag data). Most callers pass <see cref="SRgbV4"/>.Span.</param>
    /// <param name="primaries">H.273 colour primaries codepoint.</param>
    /// <param name="transfer">H.273 transfer function codepoint.</param>
    /// <param name="matrix">H.273 matrix coefficients. ICC v4.4 / PNG-3
    /// both require <see cref="MatrixCoefficients.Identity"/> for image
    /// files; defaults to that.</param>
    /// <param name="videoFullRange">Full-range (true) vs limited-range
    /// (false). PNG-3 requires full range; defaults to true.</param>
    /// <returns>A new ICC profile byte array containing the original
    /// tags plus a <c>cicp</c> tag, with the Profile ID (header MD5)
    /// recomputed per ICC v4 §7.2.18.</returns>
    /// <remarks>
    /// Layout transformation: the new tag table is one entry longer than
    /// the original (12 bytes), so all existing tag-body data is shifted
    /// down by 12 bytes and each existing tag-table entry's offset field
    /// is incremented by 12. The cicp tag body (12 bytes: 4-byte 'cicp'
    /// type signature, 4 reserved zeros, then the 4 H.273 codepoints) is
    /// appended at the end. Profile size in the header (bytes 0..3) is
    /// updated to <c>original_size + 24</c>. The Profile ID MD5 in
    /// header bytes 84..99 is recomputed over the full profile bytes
    /// with bytes 44..47 (profile flags), 64..67 (rendering intent),
    /// and 84..99 (the Profile ID itself) zeroed for the hash, per
    /// ICC v4 §7.2.18.
    /// </remarks>
    public static byte[] WithCicp(
        ReadOnlySpan<byte> baseProfile,
        ColorPrimaries primaries,
        TransferFunction transfer,
        MatrixCoefficients matrix = MatrixCoefficients.Identity,
        bool videoFullRange = true)
    {
        if (baseProfile.Length < 132)
            throw new ArgumentException($"ICC profile too short ({baseProfile.Length} bytes); minimum is 128-byte header + 4-byte tag count.", nameof(baseProfile));

        var declaredSize = (int)BinaryPrimitives.ReadUInt32BigEndian(baseProfile);
        if (declaredSize != baseProfile.Length)
            throw new ArgumentException($"ICC profile size mismatch: header says {declaredSize}, buffer is {baseProfile.Length}.", nameof(baseProfile));

        var tagCount = BinaryPrimitives.ReadUInt32BigEndian(baseProfile[128..]);
        var tagTableEnd = 132 + (int)tagCount * 12;
        if (tagTableEnd > baseProfile.Length)
            throw new ArgumentException($"ICC profile tag table claims {tagCount} entries but body is too short.", nameof(baseProfile));

        // New buffer: original size + 12 bytes (one new tag-table entry)
        // + 12 bytes (the cicp tag body).
        var newSize = baseProfile.Length + 24;
        var result = new byte[newSize];

        // Copy header (0..127) verbatim.
        baseProfile[..128].CopyTo(result);
        // Copy tag count: incremented by 1.
        BinaryPrimitives.WriteUInt32BigEndian(result.AsSpan(128), tagCount + 1);
        // Copy existing tag-table entries (each 12 bytes) and bump each
        // entry's offset field by 12 (their tag bodies shift down to make
        // room for the new entry slot at the end of the table).
        for (var i = 0; i < tagCount; i++)
        {
            var srcEntry = baseProfile.Slice(132 + i * 12, 12);
            var dstEntry = result.AsSpan(132 + i * 12, 12);
            srcEntry.CopyTo(dstEntry);
            var oldOffset = BinaryPrimitives.ReadUInt32BigEndian(dstEntry[4..]);
            BinaryPrimitives.WriteUInt32BigEndian(dstEntry[4..], oldOffset + 12);
        }

        // Position for the NEW cicp tag-table entry: right after the
        // existing ones, still inside the (now larger) tag table.
        var newEntryOffset = 132 + (int)tagCount * 12;
        // Position for the NEW cicp tag body: at the very end. Existing
        // bodies sit between [oldTagTableEnd + 12, newSize - 12).
        var newTagBodyOffset = newSize - 12;

        // Write the new tag-table entry: 4-byte 'cicp' signature, 4-byte
        // offset to body, 4-byte body size.
        WriteSignature(result.AsSpan(newEntryOffset, 4), "cicp"u8);
        BinaryPrimitives.WriteUInt32BigEndian(result.AsSpan(newEntryOffset + 4), (uint)newTagBodyOffset);
        BinaryPrimitives.WriteUInt32BigEndian(result.AsSpan(newEntryOffset + 8), 12u);

        // Copy existing tag bodies forward by 12 bytes (they sat at
        // [old tagTableEnd, declaredSize); they now sit at
        // [new tagTableEnd, declaredSize + 12)). The new tag table is
        // 12 bytes larger so newTagTableEnd == old tagTableEnd + 12.
        baseProfile[tagTableEnd..].CopyTo(result.AsSpan(tagTableEnd + 12));

        // Write the new cicp tag body (12 bytes).
        WriteSignature(result.AsSpan(newTagBodyOffset, 4), "cicp"u8);
        // bytes 4..7: reserved zeros (already zero from `new byte[]`)
        result[newTagBodyOffset + 8] = (byte)primaries;
        result[newTagBodyOffset + 9] = (byte)transfer;
        result[newTagBodyOffset + 10] = (byte)matrix;
        result[newTagBodyOffset + 11] = (byte)(videoFullRange ? 1 : 0);

        // Update the profile size field in the header.
        BinaryPrimitives.WriteUInt32BigEndian(result, (uint)newSize);

        // Recompute the Profile ID MD5 per ICC v4 §7.2.18. The hash
        // covers the entire profile with three header fields zeroed:
        // flags (44..47), rendering intent (64..67), and Profile ID
        // itself (84..99). Save and restore.
        Span<byte> savedFlags = stackalloc byte[4];
        Span<byte> savedIntent = stackalloc byte[4];
        Span<byte> savedId = stackalloc byte[16];
        result.AsSpan(44, 4).CopyTo(savedFlags);
        result.AsSpan(64, 4).CopyTo(savedIntent);
        result.AsSpan(84, 16).CopyTo(savedId);
        result.AsSpan(44, 4).Clear();
        result.AsSpan(64, 4).Clear();
        result.AsSpan(84, 16).Clear();

        Span<byte> md5 = stackalloc byte[16];
        MD5.HashData(result, md5);

        savedFlags.CopyTo(result.AsSpan(44, 4));
        savedIntent.CopyTo(result.AsSpan(64, 4));
        md5.CopyTo(result.AsSpan(84, 16));

        return result;
    }

    private static void WriteSignature(Span<byte> dst, ReadOnlySpan<byte> sig)
    {
        // 4-byte signature literal (e.g. "cicp"u8). Spec stores these as
        // raw ASCII in the file, NOT byte-swapped on either endian.
        sig.CopyTo(dst);
    }
}
