#!/usr/bin/env bash
# Build JxrDecApp / JxrEncApp from jxrlib for the oracle tests.
# See README.md for context.
#
# Runs on Windows (clang, no MSVC/CMake) and on Linux — CI uses the Linux path,
# so this script is what makes the JXR oracle a real gate rather than a dev-box
# nicety. The two platforms need different flags; see PLATFORM FLAGS below.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
SRC="$HERE/jxrlib-src"
BIN="$HERE/bin"
mkdir -p "$BIN"

# Pinned. The whole value of this oracle is that our codestream matches *this*
# reference byte-for-byte, so an unpinned clone would let upstream silently
# redefine what "correct" means — and, now that CI builds it on every PR, turn a
# green build red for reasons unrelated to the change under review. Same
# reasoning as the SHA-256 pin in jpegenc/build.sh. This commit is jxrlib's
# current HEAD and has been since 2017; bumping it means re-validating the port.
JXRLIB_COMMIT=f7521879862b9085318e814c6157490dd9dbbdb4

if [ ! -d "$SRC" ]; then
    echo "[oracle] cloning jxrlib into $SRC"
    git clone https://github.com/4creators/jxrlib.git "$SRC"
    git -C "$SRC" checkout --quiet "$JXRLIB_COMMIT"
fi

have=$(git -C "$SRC" rev-parse HEAD)
if [ "$have" != "$JXRLIB_COMMIT" ]; then
    echo "[oracle] WARNING: $SRC is at $have, expected $JXRLIB_COMMIT"
    echo "[oracle]          delete it and re-run to get the pinned reference."
fi

# Patch image/sys/ansi.h so UINTPTR_T sizes correctly on Windows x64 / arm64.
# Upstream only checks __LP64__ which is UNIX-only; without this, strcodec.h's
# CT_ASSERT(sizeof(UINTPTR_T) == sizeof(void*)) fails to compile on Windows.
# Harmless on Linux (where __LP64__ is already right), so it is unconditional —
# both platforms then compile identical sources.
ANSI="$SRC/image/sys/ansi.h"
if grep -q '^#if __LP64__$' "$ANSI"; then
    echo "[oracle] patching $ANSI for Windows 64-bit"
    # Windows dev boxes here have `python` (which is 3.x) and no `python3`;
    # ubuntu-latest has `python3` and, since 24.04, no bare `python`. Probe by
    # *running* each candidate rather than just resolving it: Windows ships a
    # `python3.exe` App Execution Alias that exists on PATH but only opens the
    # Microsoft Store, so `command -v` alone would pick a stub that never runs.
    PY=""
    for candidate in python3 python; do
        if command -v "$candidate" > /dev/null 2>&1 && "$candidate" -c "" > /dev/null 2>&1; then
            PY="$candidate"
            break
        fi
    done
    if [ -z "$PY" ]; then
        echo "[oracle] ERROR: need python (3.x) to patch ansi.h; none found on PATH." >&2
        exit 1
    fi
    # Replace the LP64-only guard with one that also catches Windows / aarch64.
    "$PY" -c "
import sys
p = sys.argv[1]
src = open(p, 'r', encoding='utf-8', errors='replace').read()
src = src.replace(
    '#if __LP64__\n#define UINTPTR_T unsigned long long\n#define INTPTR_T long long\n#else\n#define UINTPTR_T unsigned int\n#define INTPTR_T int\n#endif',
    '#if defined(__LP64__) || defined(_WIN64) || defined(__aarch64__) || defined(_M_X64) || defined(_M_ARM64)\n#define UINTPTR_T unsigned long long\n#define INTPTR_T long long\n#else\n#define UINTPTR_T unsigned int\n#define INTPTR_T int\n#endif'
)
open(p, 'w', encoding='utf-8').write(src)
" "$ANSI"
fi

# ---------------------------------------------------------------- PLATFORM FLAGS
#
# Windows: -DWIN32 plus force-included wmsal.h, which is how jxrlib expects to
# be compiled for a Windows target.
#
# Linux: upstream's own Makefile flags, and emphatically NOT -DWIN32/wmsal.h.
# Force-including wmsal.h pulls in guiddef.h before JXRGlue.c reaches its
# `#define INITGUID`, so every DEFINE_GUID degrades to a declaration and the
# link fails on a pile of undefined GUID_PKPixelFormat* symbols. Two real gaps
# remain, both from clang 18 promoting implicit-function-declaration to an
# error, and both fixed by declaring rather than redefining:
#   * wcslen      — just needs <wchar.h>.
#   * _byteswap_ulong — an MSVC name, but jxrlib ships its own definition in
#     image/sys/strcodec.c for non-Windows targets. It is only missing a
#     prototype, so declare it (U32 is `unsigned int`, windowsmediaphoto.h:61)
#     and let the real one link. Do NOT map it to __builtin_bswap32: that would
#     silently bypass jxrlib's implementation, and the point of an oracle is to
#     run *their* code, not a lookalike.
#
# Verified equivalent, not assumed: for the same BMP, the Linux and Windows
# builds emit byte-identical .jxr codestreams at overlap 0/1/2, and Linux
# JxrDecApp reproduces the source pixels exactly.
case "$(uname -s)" in
    Linux*)
        SHIM="$BIN/linux-shim.h"
        cat > "$SHIM" <<'SHIM_EOF'
/* Generated by build.sh — declarations clang 18 requires that jxrlib omits.
   _byteswap_ulong is defined in image/sys/strcodec.c on non-Windows targets. */
#include <wchar.h>
unsigned int _byteswap_ulong(unsigned int bits);
SHIM_EOF
        CFLAGS="-include $SHIM -I. -Icommon/include -Iimage/sys -Ijxrgluelib -Ijxrtestlib -D__ANSI__ -DDISABLE_PERF_MEASUREMENT -w -O2"
        LDLIBS="-lm"
        ;;
    *)
        CFLAGS="-DWIN32 -include wmsal.h -I. -Icommon/include -Iimage/sys -Ijxrgluelib -Ijxrtestlib -D__ANSI__ -DDISABLE_PERF_MEASUREMENT -w -O2"
        LDLIBS=""
        ;;
esac

SRCS=(
    image/sys/adapthuff.c image/sys/image.c image/sys/strcodec.c
    image/sys/strPredQuant.c image/sys/strTransform.c image/sys/perfTimerANSI.c
    image/decode/decode.c image/decode/postprocess.c image/decode/segdec.c
    image/decode/strdec.c image/decode/strInvTransform.c image/decode/strPredQuantDec.c
    image/decode/JXRTranscode.c
    image/encode/encode.c image/encode/segenc.c image/encode/strenc.c
    image/encode/strFwdTransform.c image/encode/strPredQuantEnc.c
    jxrgluelib/JXRGlue.c jxrgluelib/JXRMeta.c jxrgluelib/JXRGluePFC.c
    jxrgluelib/JXRGlueJxr.c
    jxrtestlib/JXRTest.c jxrtestlib/JXRTestBmp.c jxrtestlib/JXRTestHdr.c
    jxrtestlib/JXRTestPnm.c jxrtestlib/JXRTestTif.c jxrtestlib/JXRTestYUV.c
)

cd "$SRC"

# The .exe suffix is kept on every platform: the test harness looks for these
# exact names, and a filename extension means nothing to Linux anyway.
echo "[oracle] building JxrDecApp.exe"
clang $CFLAGS -o "$BIN/JxrDecApp.exe" "${SRCS[@]}" jxrencoderdecoder/JxrDecApp.c $LDLIBS

echo "[oracle] building JxrEncApp.exe"
clang $CFLAGS -o "$BIN/JxrEncApp.exe" "${SRCS[@]}" jxrencoderdecoder/JxrEncApp.c $LDLIBS

ls -la "$BIN"/Jxr*App.exe
echo "[oracle] done"
